apiVersion: v1
kind: Service
metadata:
  name: simulator
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: simulator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: simulator
          image: ghcr.io/predictivemovement/telge-twin-simulator:2.6.39 # {"$imagepolicy": "flux-system:simulator"}
          # resources:
          #   requests:
          #     cpu: "1"
          #     memory: "1Gi"
          ports:
            - containerPort: 4000
          env:
            - name: VROOM_URL
              value: http://vroom.vroom.svc.cluster.local:3000
            - name: ELASTICSEARCH_URL
              value: http://elastic-elasticsearch.elasticsearch.svc.cluster.local:9200
            - name: PELIAS_URL
              value: http://pelias-api.pelias.svc.cluster.local:3100
            - name: STREAMS_URL
              value: http://sample-address:4001
          volumeMounts:
            - mountPath: /app/.cache
              name: cache-volume
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: 5Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simulator-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.org/websocket-services: "simulator"
spec:
  tls:
    - hosts:
        - telge.iteam.pub
      secretName: telge-simulator-tls
  rules:
    - host: telge.iteam.pub
      http:
        paths:
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: simulator
                port:
                  number: 4000
