apiVersion: v1
kind: Service
metadata:
  name: visualisation
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: visualisation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualisation
spec:
  selector:
    matchLabels:
      app: visualisation
  template:
    metadata:
      labels:
        app: visualisation
    spec:
      containers:
        - name: visualisation
          image: ghcr.io/predictivemovement/telge-twin-visualisation:2.6.65 # {"$imagepolicy": "flux-system:visualisation"}
          resources:
            requests:
              cpu: 100m
              memory: "512Mi"
          ports:
            - containerPort: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: visualisation-route
spec:
  parentRefs:
    - name: telge-http-gateway
      namespace: envoy-gateway-system
  hostnames:
    - telge.iteam.pub
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: visualisation
          port: 80
