apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: telge-baseline

patches:
- path: visualisation.yaml
- path: simulator.yaml
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: TRAFIKLAB_KEY
        value: "70fcddcbf2814c49bc93e9694ea3df53"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: LATITUDE
        value: "59.195"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: LONGITUDE
        value: "17.625"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ZOOM
        value: "9"
  target:
    kind: Deployment
    name: simulator

# Trafiklab API: https://developer.trafiklab.se/user/24158/keys
