apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simulator-ingress
spec:
  tls:
    - hosts:
        - telge-baseline.iteam.pub
      secretName: telge-baseline-prod-tls
  rules:
    - host: telge-baseline.iteam.pub
      http:
        paths:
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: simulator
                port:
                  number: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  template:
    spec:
      containers:
        - name: simulator
          image: ghcr.io/predictivemovement/telge-twin-simulator:2.6.34 # hard coded to a specific version without clustering