apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: simulator-route
spec:
  hostnames:
    - dev.telge.iteam.pub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    spec:
      containers:
        - name: simulator
          image: ghcr.io/predictivemovement/telge-twin-simulator:dev-20260424141224-db0d25d # {"$imagepolicy": "flux-system:simulator-dev"}
          imagePullPolicy: Always
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch-master.elasticsearch-dev.svc.cluster.local:9200
      initContainers:
        - name: elastic-init
          image: ghcr.io/predictivemovement/telge-twin-simulator:dev-20260424141224-db0d25d # {"$imagepolicy": "flux-system:simulator-dev"}
          imagePullPolicy: Always
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch-master.elasticsearch-dev.svc.cluster.local:9200
          command: ["node", "dist/preboot.js"]
