apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: visualisation-route
spec:
  hostnames:
    - dev.telge.iteam.pub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualisation
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
        - name: visualisation
          image: ghcr.io/predictivemovement/telge-twin-visualisation:dev-20260407131851-d241806 # {"$imagepolicy": "flux-system:visualisation-dev"}
          imagePullPolicy: Always
